title: Test
#theme: just-the-docs
#theme: jekyll-theme-architect
#bootswatch-theme: cerulean
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
